version: '3'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=vista-platform_development
  web:
    build: .
    command: /bin/sh
    volumes:
      - .:/www
    ports:
      - '3000:3000'
    depends_on:
      - db
  